apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: FindAvengerAvailability
  description: API for finding avengers to fight
  links:
   - url: http://localhost:8080/swagger-ui.html
     title: Swagger UI
  tags:
    - http
    - flask
spec:
  type: openapi
  lifecycle: production
  owner: group:guests
  system: Defendcity
  definition: some text
