
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: AvengerDatabase
  description: A simple counter service
  tags:
    - kotlin
spec:
  type: service
  lifecycle: experimental
  owner: group:guests
  system: Defendcity
  providesApis: 
    - api:FindAvengerAvailability